## Ensemble Learning

ensemble learning은 여러 학습 모델을 결합하여 우수한 성능의 모델을 생성하고 성능을 향상시킨다. simple ensemble과 advenced ensemble로 나뉜다. 
average : 여러 모델 예측치의 평균으로 최종 예측 모델 생성 
weighted average : 사용자의 의도에 따라 가중치를 부가하여 최종 예측 모델 생성 
max voting : 여러 모델의 예측 결과중 가장 많이 선정된 값으로 최종 예측 값 선정 

### Simple ensemble
average



In [3]:
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
import pandas as pd
import numpy as np

In [4]:
credData = pd.read_csv("data/ensemble_data_sample.csv", sep= ",",header = None,na_values =  "?")
credData.head()

0      1      2  3  4  5  6     7  8  9   10 11 12     13   14 15
0  b  30.83  0.000  u  g  w  v  1.25  t  t   1  f  g  202.0    0  +
1  a  58.67  4.460  u  g  q  h  3.04  t  t   6  f  g   43.0  560  +
2  a  24.50  0.500  u  g  q  h  1.50  t  f   0  f  g  280.0  824  +
3  b  27.83  1.540  u  g  w  v  3.75  t  t   5  t  g  100.0    3  +
4  b  20.17  5.625  u  g  w  v  1.71  t  f   0  f  s  120.0    0  +

In [5]:
credData.loc[credData[15] == '+', 15] = 1
credData.loc[credData[15] == '-', 15] = 0
credData.head()

0      1      2  3  4  5  6     7  8  9   10 11 12     13   14 15
0  b  30.83  0.000  u  g  w  v  1.25  t  t   1  f  g  202.0    0  1
1  a  58.67  4.460  u  g  q  h  3.04  t  t   6  f  g   43.0  560  1
2  a  24.50  0.500  u  g  q  h  1.50  t  f   0  f  g  280.0  824  1
3  b  27.83  1.540  u  g  w  v  3.75  t  t   5  t  g  100.0    3  1
4  b  20.17  5.625  u  g  w  v  1.71  t  f   0  f  s  120.0    0  1

In [6]:
credData.isnull().sum()

0     12
1     12
2      0
3      6
4      6
5      9
6      9
7      0
8      0
9      0
10     0
11     0
12     0
13    13
14     0
15     0
dtype: int64

In [7]:
print('Shape of raw data set',credData.shape)
print('Data types of data set',credData.dtypes)

Shape of raw data set (690, 16)
Data types of data set 0      object
1     float64
2     float64
3      object
4      object
5      object
6      object
7     float64
8      object
9      object
10      int64
11     object
12     object
13    float64
14      int64
15     object
dtype: object


In [8]:
newcred = credData.dropna(axis = 0)
newcred
newcred.shape

(653, 16)

In [9]:
newcred.isnull().sum()

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
dtype: int64

In [10]:
print('Shape of raw data set',credData.shape)
print('Data types of data set',credData.dtypes)

Shape of raw data set (690, 16)
Data types of data set 0      object
1     float64
2     float64
3      object
4      object
5      object
6      object
7     float64
8      object
9      object
10      int64
11     object
12     object
13    float64
14      int64
15     object
dtype: object


In [11]:
credCat = pd.get_dummies(newcred[[0,3,4,5,6,8,9,11,12]])
credCat

0_a  0_b  3_l  3_u  3_y  4_g  4_gg  4_p  5_aa  5_c  ...  6_z  8_f  8_t  \
0      0    1    0    1    0    1     0    0     0    0  ...    0    0    1   
1      1    0    0    1    0    1     0    0     0    0  ...    0    0    1   
2      1    0    0    1    0    1     0    0     0    0  ...    0    0    1   
3      0    1    0    1    0    1     0    0     0    0  ...    0    0    1   
4      0    1    0    1    0    1     0    0     0    0  ...    0    0    1   
..   ...  ...  ...  ...  ...  ...   ...  ...   ...  ...  ...  ...  ...  ...   
685    0    1    0    0    1    0     0    1     0    0  ...    0    1    0   
686    1    0    0    1    0    1     0    0     0    1  ...    0    1    0   
687    1    0    0    0    1    0     0    1     0    0  ...    0    1    0   
688    0    1    0    1    0    1     0    0     1    0  ...    0    1    0   
689    0    1    0    1    0    1     0    0     0    1  ...    0    1    0   

     9_f  9_t  11_f  11_t  12_g  12_p  12_s  
0      0    1     1     0     1     0     0  
1      0    1     1     0     1     0     0  
2      1    0     1     0     1     0     0  
3      0    1     0     1     1     0     0  
4      1    0     1     0     0     0     1  
..   ...  ...   ...   ...   ...   ...   ...  
685    1    0     1     0     1     0     0  
686    0    1     0     1     1     0     0  
687    0    1     0     1     1     0     0  
688    1    0     1     0     1     0     0  
689    1    0     0     1     1     0     0  

[653 rows x 40 columns]

In [12]:
credNum = newcred[[1,2,7,10,13,14]]
credNum

1       2     7   10     13   14
0    30.83   0.000  1.25   1  202.0    0
1    58.67   4.460  3.04   6   43.0  560
2    24.50   0.500  1.50   0  280.0  824
3    27.83   1.540  3.75   5  100.0    3
4    20.17   5.625  1.71   0  120.0    0
..     ...     ...   ...  ..    ...  ...
685  21.08  10.085  1.25   0  260.0    0
686  22.67   0.750  2.00   2  200.0  394
687  25.25  13.500  2.00   1  200.0    1
688  17.92   0.205  0.04   0  280.0  750
689  35.00   3.375  8.29   0    0.0    0

[653 rows x 6 columns]

In [13]:
X = pd.concat([credCat, credNum], axis =1)
X.shape

(653, 46)

In [14]:
y = newcred[15]
y.shape

(653,)

In [15]:
from sklearn.preprocessing import MinMaxScaler
minmaxScaler = MinMaxScaler()

X_trans = pd.DataFrame(minmaxScaler.fit_transform(X))

X_trans.head()

0    1    2    3    4    5    6    7    8    9   ...   36   37   38   39  \
0  0.0  1.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  0.0  1.0  0.0  0.0   
1  1.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  0.0  1.0  0.0  0.0   
2  1.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  0.0  1.0  0.0  0.0   
3  0.0  1.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  1.0  1.0  0.0  0.0   
4  0.0  1.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  1.0   

         40        41        42        43      44       45  
0  0.271111  0.000000  0.043860  0.014925  0.1010  0.00000  
1  0.713016  0.159286  0.106667  0.089552  0.0215  0.00560  
2  0.170635  0.017857  0.052632  0.000000  0.1400  0.00824  
3  0.223492  0.055000  0.131579  0.074627  0.0500  0.00003  
4  0.101905  0.200893  0.060000  0.000000  0.0600  0.00000  

[5 rows x 46 columns]

In [16]:
# y_test

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X_trans, y, test_size = 0.3, random_state = 123)
y_train = y_train.astype('int')
y_test = y_test.astype('int')
# y_train = y_train.astype('int64')

y_train


370    0
313    0
64     1
384    0
272    0
      ..
103    0
338    0
400    0
383    0
538    0
Name: 15, Length: 457, dtype: int64

In [18]:
model1 = LogisticRegression(random_state=123)
model2 = KNeighborsClassifier(n_neighbors=5)
model3 = RandomForestClassifier(n_estimators=500)

In [19]:
model1.fit(X_train, y_train)
model2.fit(X_train, y_train)
model3.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=500,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [20]:
pred1 = model1.predict(X_test)
pred2 = model2.predict(X_test)
pred3 = model3.predict(X_test)

In [21]:
ensemblepred = (pred1 + pred2 + pred3)/3
ensemblepred[0:4]

array([0., 0., 1., 1.])

In [22]:
print(model1.classes_)
print(model2.classes_)
print(model3.classes_)

[0 1]
[0 1]
[0 1]


In [23]:
pred = np.argmax(ensemblepred)#, axis =1)
pred

2

In [24]:
print(y_test.shape, ensemblepred.shape)
print(ensemblepred.round())

(196,) (196,)
[0. 0. 1. 1. 0. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 1.
 0. 0. 0. 0. 0. 1. 1. 0. 1. 0. 0. 1. 1. 0. 1. 0. 0. 0. 0. 0. 1. 0. 1. 0.
 1. 0. 1. 1. 1. 1. 1. 0. 1. 0. 0. 1. 1. 0. 1. 1. 1. 0. 0. 1. 0. 1. 1. 1.
 1. 1. 1. 1. 1. 0. 1. 1. 0. 1. 1. 1. 0. 1. 0. 1. 0. 1. 0. 0. 1. 0. 0. 0.
 1. 0. 1. 0. 0. 1. 0. 1. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 1. 1.
 0. 0. 1. 0. 0. 1. 0. 1. 1. 0. 0. 1. 0. 0. 1. 1. 0. 1. 1. 1. 1. 0. 1. 0.
 1. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 0. 1. 1. 1. 0. 1. 0. 0. 0. 1. 1. 1. 0.
 0. 0. 1. 0. 1. 0. 0. 0. 1. 1. 1. 1. 1. 1. 0. 0. 1. 1. 0. 0. 0. 0. 1. 0.
 0. 1. 0. 1.]


In [25]:
confusionMatrix = confusion_matrix(y_test, ensemblepred.round())
print(confusionMatrix)

[[96 11]
 [ 7 82]]


In [26]:
print(classification_report(y_test, ensemblepred.round()))

              precision    recall  f1-score   support

           0       0.93      0.90      0.91       107
           1       0.88      0.92      0.90        89

    accuracy                           0.91       196
   macro avg       0.91      0.91      0.91       196
weighted avg       0.91      0.91      0.91       196



### Weighted Averaging Ensemble
1st Generation

In [28]:
ensemblepred=(pred1 *0.60 + pred2 * 0.20 + pred3 * 0.20)

In [31]:
ensemblepred[0:4]

array([0., 0., 1., 1.])

In [32]:
print(model1.classes_)
print(model2.classes_)
print(model3.classes_)

[0 1]
[0 1]
[0 1]


In [34]:
pred = np.argmax(ensemblepred,axis = 0)
pred

2

In [37]:
confusionMatrix = confusion_matrix(y_test, ensemblepred.round())
print(confusionMatrix)

[[93 14]
 [ 8 81]]


In [38]:
print(classification_report(y_test, ensemblepred.round()))

              precision    recall  f1-score   support

           0       0.92      0.87      0.89       107
           1       0.85      0.91      0.88        89

    accuracy                           0.89       196
   macro avg       0.89      0.89      0.89       196
weighted avg       0.89      0.89      0.89       196



2nd Generation

In [39]:
ensemblepred=(pred1 *0.70+pred2 * 0.15+pred3 * 0.15)

In [40]:
ensemblepred[0:4]

array([0., 0., 1., 1.])

In [41]:
print(model1.classes_)
print(model2.classes_)
print(model3.classes_)

[0 1]
[0 1]
[0 1]


In [42]:
pred = np.argmax(ensemblepred,axis = 0)
pred

2

In [43]:
confusionMatrix = confusion_matrix(y_test, ensemblepred.round())
print(confusionMatrix)

[[93 14]
 [ 8 81]]


In [44]:
print(classification_report(y_test, ensemblepred.round()))

              precision    recall  f1-score   support

           0       0.92      0.87      0.89       107
           1       0.85      0.91      0.88        89

    accuracy                           0.89       196
   macro avg       0.89      0.89      0.89       196
weighted avg       0.89      0.89      0.89       196



### Max Votion 

In [47]:
from sklearn.ensemble import VotingClassifier

In [48]:
model1 = LogisticRegression(random_state=123)
model2 = KNeighborsClassifier(n_neighbors=5)
model3 = RandomForestClassifier(n_estimators=500)

In [49]:
model = VotingClassifier(estimators=[('lr', model1),('knn', model2),('rf', model3)], voting= 'hard')

In [50]:
model.fit(X_train,y_train)

VotingClassifier(estimators=[('lr',
                              LogisticRegression(C=1.0, class_weight=None,
                                                 dual=False, fit_intercept=True,
                                                 intercept_scaling=1,
                                                 l1_ratio=None, max_iter=100,
                                                 multi_class='auto',
                                                 n_jobs=None, penalty='l2',
                                                 random_state=123,
                                                 solver='lbfgs', tol=0.0001,
                                                 verbose=0, warm_start=False)),
                             ('knn',
                              KNeighborsClassifier(algorithm='auto',
                                                   leaf_size=30,
                                                   metric='minkowski',
                                                 

In [51]:
model.score(X_test,y_test)

0.9081632653061225

In [53]:
preds = model.predict(X_test)
preds

array([0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1])

In [54]:
print(confusion_matrix(y_test, preds))

[[96 11]
 [ 7 82]]


In [55]:
print(classification_report(y_test, preds))

              precision    recall  f1-score   support

           0       0.93      0.90      0.91       107
           1       0.88      0.92      0.90        89

    accuracy                           0.91       196
   macro avg       0.91      0.91      0.91       196
weighted avg       0.91      0.91      0.91       196

